import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceRoleKey) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

async function setupDatabase() {
  console.log("Setting up Supabase tables...");

  try {
    // Create supervisors table
    console.log("Creating supervisors table...");
    const { error: supError } = await supabase.rpc("exec", {
      sql: `
        CREATE TABLE IF NOT EXISTS supervisors (
          username TEXT PRIMARY KEY,
          password TEXT NOT NULL,
          full_name TEXT,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
      `,
    });
    if (supError && !supError.message?.includes("already exists")) {
      console.error("Error creating supervisors table:", supError);
    } else {
      console.log("✓ Supervisors table created");
    }

    // Create authorized_participants table
    console.log("Creating authorized_participants table...");
    const { error: partError } = await supabase.rpc("exec", {
      sql: `
        CREATE TABLE IF NOT EXISTS authorized_participants (
          msisdn TEXT PRIMARY KEY,
          nom_cod TEXT NOT NULL,
          wilaya TEXT NOT NULL,
          region TEXT NOT NULL,
          distributeur_actuel TEXT NOT NULL,
          supervisor_username TEXT NOT NULL REFERENCES supervisors(username),
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
      `,
    });
    if (partError && !partError.message?.includes("already exists")) {
      console.error("Error creating authorized_participants table:", partError);
    } else {
      console.log("✓ Authorized participants table created");
    }

    // Create responses table
    console.log("Creating responses table...");
    const { error: respError } = await supabase.rpc("exec", {
      sql: `
        CREATE TABLE IF NOT EXISTS responses (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          msisdn TEXT NOT NULL REFERENCES authorized_participants(msisdn),
          choix_1 TEXT NOT NULL,
          choix_2 TEXT NOT NULL,
          choix_3 TEXT NOT NULL,
          choix_4 TEXT NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          UNIQUE(msisdn)
        );
      `,
    });
    if (respError && !respError.message?.includes("already exists")) {
      console.error("Error creating responses table:", respError);
    } else {
      console.log("✓ Responses table created");
    }

    // Create indexes
    console.log("Creating indexes...");
    const { error: indexError } = await supabase.rpc("exec", {
      sql: `
        CREATE INDEX IF NOT EXISTS idx_authorized_participants_supervisor ON authorized_participants(supervisor_username);
        CREATE INDEX IF NOT EXISTS idx_responses_msisdn ON responses(msisdn);
        CREATE INDEX IF NOT EXISTS idx_responses_created_at ON responses(created_at);
      `,
    });
    if (indexError && !indexError.message?.includes("already exists")) {
      console.error("Error creating indexes:", indexError);
    } else {
      console.log("✓ Indexes created");
    }

    console.log("\n✓ Database setup completed successfully!");
  } catch (error) {
    console.error("Setup failed:", error);
    process.exit(1);
  }
}

setupDatabase();
