-- Create supervisors table
CREATE TABLE IF NOT EXISTS supervisors (
  username TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  full_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create authorized_participants table
CREATE TABLE IF NOT EXISTS authorized_participants (
  msisdn TEXT PRIMARY KEY,
  nom_cod TEXT NOT NULL,
  wilaya TEXT NOT NULL,
  region TEXT NOT NULL,
  distributeur_actuel TEXT NOT NULL,
  supervisor_username TEXT NOT NULL REFERENCES supervisors(username),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create responses table
CREATE TABLE IF NOT EXISTS responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msisdn TEXT NOT NULL REFERENCES authorized_participants(msisdn),
  choix_1 TEXT NOT NULL,
  choix_2 TEXT NOT NULL,
  choix_3 TEXT NOT NULL,
  choix_4 TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(msisdn)
);

-- Create indexes for better query performance
CREATE INDEX idx_authorized_participants_supervisor ON authorized_participants(supervisor_username);
CREATE INDEX idx_responses_msisdn ON responses(msisdn);
CREATE INDEX idx_responses_created_at ON responses(created_at);

-- Add comment for documentation
COMMENT ON TABLE supervisors IS 'Stores supervisor account information with username and password for authentication';
COMMENT ON TABLE authorized_participants IS 'Stores authorized participants (points of sale) with their details and assigned supervisor';
COMMENT ON TABLE responses IS 'Stores voting responses from participants with their 4 ranked distributor choices';
